# Generated by Claude Sonnet 5
# Reviewed by me (somewhat)

"""
opcodeVisualizer.py

GUI visualizer for stakku VM bytecode (binary opcode files).

Usage:
    python3 opcodeVisualizer.py [path/to/bytecode.bin]

If no path is given, a file-open dialog appears on launch.

Controls:
    Space       Toggle auto-run (play/pause) at ~2 instructions/sec
    Right / n   Step forward one instruction
    Left  / p   Step backward one instruction (undo, via snapshot history)
    r           Reset to start
    o           Open a different bytecode file
    q / Esc     Quit

Bytecode format (matches stakku's OpCode enum, one byte per opcode):
    0x00 OP_HALT        (no operand)
    0x01 OP_PUSH_NUM    8-byte little-endian double operand
    0x02 OP_ADD         (no operand)
    0x03 OP_SUB         (no operand)
    0x04 OP_MUL         (no operand)
    0x05 OP_DIV         (no operand)
    0x06 OP_MOD         (no operand)
    0x07 OP_EQ          (no operand)
    0x08 OP_LT          (no operand)
    0x09 OP_GT          (no operand)
    0x0A OP_LE          (no operand)
    0x0B OP_GE          (no operand)
    0x0C OP_NEQ         (no operand)
    0x0D OP_AND         (no operand)
    0x0E OP_OR          (no operand)
    0x0F OP_NOT         (no operand)
    0x10 OP_XOR         (no operand)
    0x11 OP_DUP         (no operand)
    0x12 OP_DROP        (no operand)
    0x13 OP_SWAP        (no operand)
    0x14 OP_OVER        (no operand)
    0x15 OP_ROT         (no operand)
    0x16 OP_PRINT       (no operand)
    0x17 OP_EMIT        (no operand)
    0x18 OP_CR          (no operand)
    0x19 OP_CLEAR       (no operand)
    0x1A OP_JMP         2-byte little-endian uint16 address operand
    0x1B OP_JMP_IF_Z    2-byte little-endian uint16 address operand
    0x1C OP_CALL        2-byte little-endian uint16 address operand
    0x1D OP_RETURN      (no operand)
    0x1E OP_BYE         (no operand)

NOTE on operand byte order: the header only says "unsigned 16 bit addr" /
"8 bytes ... (double)" without specifying endianness. This tool assumes
little-endian (typical for x86/ARM native writes via e.g. ofstream.write on
a raw double/uint16_t). If your compiler/VM writes big-endian, flip
ENDIAN below.
"""

import math
import struct
import sys
import tkinter as tk
from tkinter import filedialog, messagebox
from dataclasses import dataclass, field
from typing import Optional

ENDIAN = "<"  # "<" little-endian, ">" big-endian — see note above

# --- Opcode table: value -> (mnemonic, operandSizeInBytes) ---------------
OPCODES = {
    0x00: ("OP_HALT", 0),
    0x01: ("OP_PUSH_NUM", 8),
    0x02: ("OP_ADD", 0),
    0x03: ("OP_SUB", 0),
    0x04: ("OP_MUL", 0),
    0x05: ("OP_DIV", 0),
    0x06: ("OP_MOD", 0),
    0x07: ("OP_EQ", 0),
    0x08: ("OP_LT", 0),
    0x09: ("OP_GT", 0),
    0x0A: ("OP_LE", 0),
    0x0B: ("OP_GE", 0),
    0x0C: ("OP_NEQ", 0),
    0x0D: ("OP_AND", 0),
    0x0E: ("OP_OR", 0),
    0x0F: ("OP_NOT", 0),
    0x10: ("OP_XOR", 0),
    0x11: ("OP_DUP", 0),
    0x12: ("OP_DROP", 0),
    0x13: ("OP_SWAP", 0),
    0x14: ("OP_OVER", 0),
    0x15: ("OP_ROT", 0),
    0x16: ("OP_PRINT", 0),
    0x17: ("OP_EMIT", 0),
    0x18: ("OP_CR", 0),
    0x19: ("OP_CLEAR", 0),
    0x1A: ("OP_JMP", 2),
    0x1B: ("OP_JMP_IF_Z", 2),
    0x1C: ("OP_CALL", 2),
    0x1D: ("OP_RETURN", 0),
    0x1E: ("OP_BYE", 0),
}

BG = "#1e1e1e"
FG = "#e0e0e0"
ACCENT = "#3a7bd5"
STACK_COLOR = "#5fd97a"
CALLSTACK_COLOR = "#d5a63a"
ERROR_COLOR = "#e05c5c"
FONT_MONO = ("Menlo", 12)
FONT_MONO_BOLD = ("Menlo", 12, "bold")


@dataclass
class Instruction:
    address: int          # byte offset where this instruction starts
    opcode: int
    mnemonic: str
    operand: Optional[float] = None
    length: int = 1        # total bytes (opcode + operand)


@dataclass
class VmState:
    pc: int = 0                 # index into instructions list
    dataStack: list = field(default_factory=list)
    callStack: list = field(default_factory=list)
    output: str = ""
    halted: bool = False
    error: Optional[str] = None


def decodeBytecode(rawBytes: bytes) -> list[Instruction]:
    """Decode raw bytes into a linear list of Instruction objects."""
    instructions = []
    i = 0
    n = len(rawBytes)
    while i < n:
        opcode = rawBytes[i]
        if opcode not in OPCODES:
            instructions.append(Instruction(
                i, opcode, f"??? (0x{opcode:02X})", None, 1))
            i += 1
            continue
        mnemonic, operandSize = OPCODES[opcode]
        operand = None
        if operandSize == 8:
            if i + 1 + 8 > n:
                instructions.append(Instruction(
                    i, opcode, mnemonic, None, n - i))
                break
            operand = struct.unpack_from(ENDIAN + "d", rawBytes, i + 1)[0]
        elif operandSize == 2:
            if i + 1 + 2 > n:
                instructions.append(Instruction(
                    i, opcode, mnemonic, None, n - i))
                break
            operand = struct.unpack_from(ENDIAN + "H", rawBytes, i + 1)[0]
        instructions.append(Instruction(
            i, opcode, mnemonic, operand, 1 + operandSize))
        i += 1 + operandSize
    return instructions


def buildAddressIndex(instructions: list[Instruction]) -> dict:
    """Map byte-address -> index in the instructions list (for jump targets)."""
    return {ins.address: idx for idx, ins in enumerate(instructions)}


class StakkuVisualizer:
    def __init__(self, root: tk.Tk, path: Optional[str]):
        self.root = root
        self.root.title("stakku bytecode visualizer")
        self.root.configure(bg=BG)
        self.root.geometry("980x640")

        self.instructions: list[Instruction] = []
        self.addrIndex: dict = {}
        self.history: list[VmState] = []
        self.state = VmState()
        self.autoRun = False
        self.autoRunJob = None

        self._buildLayout()
        self.root.bind("<space>", self.toggleAutoRun)
        self.root.bind("<Right>", lambda e: self.stepForward())
        self.root.bind("<Left>", lambda e: self.stepBackward())
        self.root.bind("n", lambda e: self.stepForward())
        self.root.bind("p", lambda e: self.stepBackward())
        self.root.bind("r", lambda e: self.reset())
        self.root.bind("o", lambda e: self.openFile())
        self.root.bind("q", lambda e: self.root.quit())
        self.root.bind("<Escape>", lambda e: self.root.quit())

        if path:
            self.loadFile(path)
        else:
            self.openFile()

    # ---------------------------------------------------------------- UI --
    def _buildLayout(self):
        top = tk.Frame(self.root, bg=BG)
        top.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)

        # Left: instruction listing
        leftFrame = tk.Frame(top, bg=BG)
        leftFrame.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        tk.Label(leftFrame, text="Bytecode", bg=BG, fg=FG,
                 font=FONT_MONO_BOLD).pack(anchor="w")
        listFrame = tk.Frame(leftFrame, bg=BG)
        listFrame.pack(fill=tk.BOTH, expand=True)
        self.codeListbox = tk.Listbox(
            listFrame, bg="#141414", fg=FG, font=FONT_MONO,
            selectbackground=ACCENT, activestyle="none", highlightthickness=0,
            borderwidth=0,
        )
        scrollbar = tk.Scrollbar(listFrame, command=self.codeListbox.yview)
        self.codeListbox.config(yscrollcommand=scrollbar.set)
        self.codeListbox.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)

        # Right: stacks + output + status
        rightFrame = tk.Frame(top, bg=BG, width=320)
        rightFrame.pack(side=tk.RIGHT, fill=tk.Y, padx=(10, 0))
        rightFrame.pack_propagate(False)

        tk.Label(rightFrame, text="Data Stack (top last)", bg=BG,
                 fg=FG, font=FONT_MONO_BOLD).pack(anchor="w")
        self.dataStackText = tk.Text(rightFrame, height=10, bg="#141414", fg=STACK_COLOR,
                                     font=FONT_MONO, borderwidth=0, highlightthickness=0)
        self.dataStackText.pack(fill=tk.X, pady=(0, 8))

        tk.Label(rightFrame, text="Call Stack (return addrs)",
                 bg=BG, fg=FG, font=FONT_MONO_BOLD).pack(anchor="w")
        self.callStackText = tk.Text(rightFrame, height=5, bg="#141414", fg=CALLSTACK_COLOR,
                                     font=FONT_MONO, borderwidth=0, highlightthickness=0)
        self.callStackText.pack(fill=tk.X, pady=(0, 8))

        tk.Label(rightFrame, text="Output", bg=BG, fg=FG,
                 font=FONT_MONO_BOLD).pack(anchor="w")
        self.outputText = tk.Text(rightFrame, height=10, bg="#141414", fg=FG,
                                  font=FONT_MONO, borderwidth=0, highlightthickness=0)
        self.outputText.pack(fill=tk.BOTH, expand=True, pady=(0, 8))

        self.statusLabel = tk.Label(rightFrame, text="", bg=BG, fg=FG, font=FONT_MONO,
                                    wraplength=300, justify="left")
        self.statusLabel.pack(anchor="w", pady=(4, 0))

        helpText = ("space: play/pause  \u2190/\u2192: step back/fwd\n"
                    "r: reset  o: open  q: quit")
        tk.Label(self.root, text=helpText, bg=BG, fg="#808080", font=("Menlo", 10),
                 justify="left").pack(anchor="w", padx=10, pady=(0, 8))

    # ------------------------------------------------------------- Files --
    def openFile(self):
        path = filedialog.askopenfilename(
            title="Open stakku bytecode file",
            filetypes=[("Binary files", "*.bin *.stk *.out"),
                       ("All files", "*.*")],
        )
        if path:
            self.loadFile(path)
        elif not self.instructions:
            self.statusLabel.config(text="No file loaded.", fg=ERROR_COLOR)

    def loadFile(self, path: str):
        try:
            with open(path, "rb") as f:
                rawBytes = f.read()
        except OSError as exc:
            messagebox.showerror("Error", f"Could not read {path}:\n{exc}")
            return
        self.instructions = decodeBytecode(rawBytes)
        self.addrIndex = buildAddressIndex(self.instructions)
        self.root.title(f"stakku bytecode visualizer — {path}")
        self.populateListbox()
        self.reset()

    def populateListbox(self):
        self.codeListbox.delete(0, tk.END)
        for ins in self.instructions:
            operandStr = ""
            if ins.operand is not None:
                if ins.mnemonic == "OP_PUSH_NUM":
                    operandStr = f"  {ins.operand}"
                else:
                    operandStr = f"  -> 0x{int(ins.operand):04X}"
            line = f"0x{ins.address:04X}  {ins.mnemonic}{operandStr}"
            self.codeListbox.insert(tk.END, line)

    # ---------------------------------------------------------------- VM --
    def reset(self):
        self.stopAutoRun()
        self.state = VmState()
        self.history = [self._snapshot()]
        self.refreshView()

    def _snapshot(self) -> VmState:
        return VmState(
            pc=self.state.pc,
            dataStack=list(self.state.dataStack),
            callStack=list(self.state.callStack),
            output=self.state.output,
            halted=self.state.halted,
            error=self.state.error,
        )

    def currentInstruction(self) -> Optional[Instruction]:
        if 0 <= self.state.pc < len(self.instructions):
            return self.instructions[self.state.pc]
        return None

    def stepForward(self):
        if not self.instructions:
            return
        if self.state.halted or self.state.error:
            self.stopAutoRun()
            return

        ins = self.currentInstruction()
        if ins is None:
            self.state.halted = True
            self.refreshView()
            return

        try:
            self._execute(ins)
        except IndexError:
            self.state.error = f"Stack underflow at 0x{
                ins.address:04X} ({ins.mnemonic})"
        except ZeroDivisionError:
            self.state.error = f"Division by zero at 0x{
                ins.address:04X} ({ins.mnemonic})"
        except KeyError:
            self.state.error = f"Unknown jump target at 0x{
                ins.address:04X} ({ins.mnemonic})"

        self.history.append(self._snapshot())
        self.refreshView()

        if self.state.halted or self.state.error:
            self.stopAutoRun()

    def stepBackward(self):
        if len(self.history) <= 1:
            return
        self.history.pop()
        self.state = self._cloneState(self.history[-1])
        self.refreshView()

    @staticmethod
    def _cloneState(s: VmState) -> VmState:
        return VmState(pc=s.pc, dataStack=list(s.dataStack), callStack=list(s.callStack),
                       output=s.output, halted=s.halted, error=s.error)

    def _execute(self, ins: Instruction):
        s = self.state
        ds = s.dataStack
        mnem = ins.mnemonic

        if mnem == "OP_HALT" or mnem == "OP_BYE":
            s.halted = True
            return
        elif mnem == "OP_PUSH_NUM":
            ds.append(ins.operand)
        elif mnem == "OP_ADD":
            b, a = ds.pop(), ds.pop()
            ds.append(a + b)
        elif mnem == "OP_SUB":
            b, a = ds.pop(), ds.pop()
            ds.append(a - b)
        elif mnem == "OP_MUL":
            b, a = ds.pop(), ds.pop()
            ds.append(a * b)
        elif mnem == "OP_DIV":
            b, a = ds.pop(), ds.pop()
            ds.append(a / b)
        elif mnem == "OP_EQ":
            b, a = ds.pop(), ds.pop()
            ds.append(-1.0 if a == b else 0.0)
        elif mnem == "OP_LT":
            b, a = ds.pop(), ds.pop()
            ds.append(-1.0 if a < b else 0.0)
        elif mnem == "OP_GT":
            b, a = ds.pop(), ds.pop()
            ds.append(-1.0 if a > b else 0.0)
        elif mnem == "OP_LE":
            b, a = ds.pop(), ds.pop()
            ds.append(-1.0 if a <= b else 0.0)
        elif mnem == "OP_GE":
            b, a = ds.pop(), ds.pop()
            ds.append(-1.0 if a >= b else 0.0)
        elif mnem == "OP_NEQ":
            b, a = ds.pop(), ds.pop()
            ds.append(-1.0 if a != b else 0.0)
        elif mnem == "OP_MOD":
            b, a = ds.pop(), ds.pop()
            if b == 0:
                raise ZeroDivisionError
            result = a - b * math.floor(a / b)
            if result == -0.0:
                result = 0.0
            ds.append(result)
        elif mnem == "OP_AND":
            b, a = ds.pop(), ds.pop()
            ds.append(float(self._safe_int(a) & self._safe_int(b)))
        elif mnem == "OP_OR":
            b, a = ds.pop(), ds.pop()
            ds.append(float(self._safe_int(a) | self._safe_int(b)))
        elif mnem == "OP_NOT":
            a = ds.pop()
            ds.append(float(~self._safe_int(a)))
        elif mnem == "OP_XOR":
            b, a = ds.pop(), ds.pop()
            ds.append(float(self._safe_int(a) ^ self._safe_int(b)))
        elif mnem == "OP_DUP":
            ds.append(ds[-1])
        elif mnem == "OP_DROP":
            ds.pop()
        elif mnem == "OP_SWAP":
            ds[-1], ds[-2] = ds[-2], ds[-1]
        elif mnem == "OP_OVER":
            ds.append(ds[-2])
        elif mnem == "OP_ROT":
            x, y, z = ds[-3], ds[-2], ds[-1]
            ds[-3], ds[-2], ds[-1] = y, z, x
        elif mnem == "OP_PRINT":
            s.output += self._formatNumber(ds.pop())
        elif mnem == "OP_EMIT":
            s.output += chr(int(ds.pop()) & 0xFF)
        elif mnem == "OP_CR":
            s.output += "\n"
        elif mnem == "OP_CLEAR":
            ds.clear()
        elif mnem == "OP_JMP":
            s.pc = self.addrIndex[int(ins.operand)]
            return
        elif mnem == "OP_JMP_IF_Z":
            top = ds.pop()
            if top == 0:
                s.pc = self.addrIndex[int(ins.operand)]
                return
        elif mnem == "OP_CALL":
            s.callStack.append(s.pc + 1)
            s.pc = self.addrIndex[int(ins.operand)]
            return
        elif mnem == "OP_RETURN":
            if not s.callStack:
                s.halted = True
                return
            s.pc = s.callStack.pop()
            return
        else:
            s.error = f"Unimplemented/unknown opcode {
                mnem} at 0x{ins.address:04X}"
            return

        s.pc += 1

    @staticmethod
    def _safe_int(v: float) -> int:
        if v != v:
            return 0
        if v == float('inf'):
            return 9223372036854775807
        if v == float('-inf'):
            return -9223372036854775808
        if v >= 9223372036854775807.0:
            return 9223372036854775807
        if v <= -9223372036854775808.0:
            return -9223372036854775808
        return int(v)

    @staticmethod
    def _formatNumber(n: float) -> str:
        return str(int(n)) if n == int(n) else str(n)

    # -------------------------------------------------------- Auto-run ---
    def toggleAutoRun(self, event=None):
        if self.autoRun:
            self.stopAutoRun()
        else:
            self.autoRun = True
            self._autoRunTick()

    def stopAutoRun(self):
        self.autoRun = False
        if self.autoRunJob is not None:
            self.root.after_cancel(self.autoRunJob)
            self.autoRunJob = None

    def _autoRunTick(self):
        if not self.autoRun:
            return
        if self.state.halted or self.state.error:
            self.stopAutoRun()
            return
        self.stepForward()
        self.autoRunJob = self.root.after(500, self._autoRunTick)

    # ------------------------------------------------------------- View --
    def refreshView(self):
        self.codeListbox.selection_clear(0, tk.END)
        if 0 <= self.state.pc < len(self.instructions):
            self.codeListbox.selection_set(self.state.pc)
            self.codeListbox.see(self.state.pc)

        self.dataStackText.delete("1.0", tk.END)
        for v in self.state.dataStack:
            self.dataStackText.insert(tk.END, f"{self._formatNumber(v)}\n")

        self.callStackText.delete("1.0", tk.END)
        for addr in self.state.callStack:
            self.callStackText.insert(tk.END, f"0x{addr:04X}\n")

        self.outputText.delete("1.0", tk.END)
        self.outputText.insert(tk.END, self.state.output)

        if self.state.error:
            self.statusLabel.config(
                text=f"ERROR: {self.state.error}", fg=ERROR_COLOR)
        elif self.state.halted:
            self.statusLabel.config(text="Halted.", fg=FG)
        else:
            ins = self.currentInstruction()
            label = f"PC=0x{ins.address:04X} next: {
                ins.mnemonic}" if ins else "PC out of range"
            playState = "playing" if self.autoRun else "paused"
            self.statusLabel.config(text=f"{label}  [{playState}]", fg=FG)


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else None
    root = tk.Tk()
    StakkuVisualizer(root, path)
    root.mainloop()


if __name__ == "__main__":
    main()
